#!/usr/bin/env python3
"""
Build the shipped engine recording and its rpm map from the source preview.

  python3 scripts/sound/prepare-engine.py <fs496171 preview .mp3>

Source (see src/app/sound/samples/CREDITS.txt): "Import car revs on Chassis Dyno with Turbo.wav" by editboy23 on Freesound,
CC0 1.0. A Toyota Supra on a chassis dyno: no Doppler, no wind, no other cars. The 35 s take holds a slow rev, a hard pull to the
limiter, an overrun, and a few seconds of steady idle at the end. The parts used are the rising pull (under power) and the fall after
it with the idle it settles into (off power): the same engine, microphone and room, so crossing between them stays one engine.

Steps: decode, mix to mono, cut 11.0 s to the end, peak-normalise to −1 dBFS, write lossless FLAC (the source is already a lossy preview,
so no second lossy encode). Then write src/app/sound/samples/engine.ts from scripts/sound/supra.maps.json, which holds firing
frequency (Hz, ascending) against position in the source file for each part; they were tracked from the spectrogram, checked by
rendering them through the real playback code, and shifted here by the cut.

Requires numpy and soundfile. macOS afconvert decodes the mp3.
"""
import json
import os
import subprocess
import sys
import tempfile

import numpy as np
import soundfile as sf

CUT = (11.0, 35.46)
POWER_RUN = (11.9, 25.3)
COAST_RUN = (26.0, 28.9)
# Both voices are played over the same physical engine speeds, so a crossfade never changes pitch.
# Rev curves: [position in the car's rev range 0..1, firing frequency Hz]. The pull's own floor is its slow rev at 165 Hz; the
# overrun voice also has the take's real idle (~65 Hz) at the bottom, climbing to meet the pull's pitch by 30 % of the range.
POWER_REV = [[0, 165.0], [0.3, 165.0], [1, 355.0]]
COAST_REV = [[0, 65.5], [0.3, 165.0], [1, 355.0]]
COAST_TRIM_DB = -3.0

here = os.path.dirname(os.path.abspath(__file__))
repo = os.path.abspath(os.path.join(here, "..", ".."))
out_dir = os.path.join(repo, "src", "app", "sound", "samples")


def main():
    src = sys.argv[1]
    wav = tempfile.mktemp(suffix=".wav")
    subprocess.run(["afconvert", "-f", "WAVE", "-d", "LEI16", src, wav], check=True)
    x, sr = sf.read(wav, always_2d=True)
    os.remove(wav)
    x = x.mean(axis=1)
    a, b = int(CUT[0] * sr), int(CUT[1] * sr)
    x = x[a:b]
    scale = 0.891 / np.abs(x).max()
    x = x * scale
    sf.write(os.path.join(out_dir, "engine.flac"), x, sr, format="FLAC", subtype="PCM_16")

    def rms(seg):
        s = x[int((seg[0] - CUT[0]) * sr) : int((seg[1] - CUT[0]) * sr)]
        return float(np.sqrt(np.mean(s * s)))

    gain_coast = round(rms(POWER_RUN) / rms(COAST_RUN) * 10 ** (COAST_TRIM_DB / 20), 3)
    maps = json.load(open(os.path.join(here, "supra.maps.json")))

    def voice(name, gain, rev):
        m = maps[name]
        assert m["sr"] == sr, (m["sr"], sr)
        at = [round(v - CUT[0] * sr, 1) for v in m["at"]]
        return (
            f"  {name}: {{\n"
            f"    url,\n"
            f"    map: {{ sr: {sr}, f0: {json.dumps(m['f0'])}, at: {json.dumps(at)} }},\n"
            f"    gain: {gain},\n"
            f"    rev: {json.dumps(rev)},\n"
            f"  }},\n"
        )

    ts = (
        "// Generated by scripts/sound/prepare-engine.py: do not edit by hand.\n"
        "import type { EngineSamples } from '../samples';\n"
        "import url from './engine.flac?url';\n\n"
        "/**\n"
        " * One recording, two parts of it: a hard pull (power) and the overrun after it (coast). Each map pairs a firing\n"
        " * frequency with where the recording is doing it. See CREDITS.txt for the source and licence.\n"
        " */\n"
        "export const ENGINE_SAMPLES: EngineSamples = {\n" + voice("power", 1.0, POWER_REV) + voice("coast", gain_coast, COAST_REV) + "};\n"
    )
    open(os.path.join(out_dir, "engine.ts"), "w").write(ts)
    print(f"wrote engine.flac ({(b - a) / sr:.1f} s @ {sr} Hz, scale {scale:.3f}) and engine.ts; coast gain {gain_coast}")


if __name__ == "__main__":
    main()
